
trigger: none
pr: none

parameters:
  - name: packageVersion
    displayName: NuGet Package Version
    type: string
    default: '9.1.0'

pool: default

variables:
  solution: 'src/DevInstance.BlazorToolkit.csproj'
  version: ${{ parameters.packageVersion }}
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  artifactName: 'drop'
  nugetFeedUrl: 'https://www.nuget.org/packages/DevInstance.BlazorToolkit/'

steps:
# Step 1: Restore NuGet Packages  
- task: UseDotNet@2
  displayName: 'Use .NET 9.x'
  inputs:
    version: 9.x

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

# Step 2: Build the Solution and pack NuGet Package
- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# Step 3: Push NuGet Package
- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet package'
  inputs:
    command: 'pack'
    packagesToPack: '$(solution)'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'version'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Push to NuGet.org'
  inputs:
    command: 'push'
    publishVstsFeed: false
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NugetCon'
