trigger:
- master

pool: default

variables:
  solution: '**/DevInstance.BlazorToolkit.sln'
  buildConfiguration: 'Release'
  nugetFeedUrl: 'https://www.nuget.org/packages/DevInstance.BlazorToolkit/'  # For internal feeds
  # nugetApiKey: $(NuGetApiKey)  # Store this in pipeline secrets  

steps:
# Step 1: Restore NuGet Packages
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 5.8'
  inputs:
    versionSpec: 5.8

- task: UseDotNet@2
  displayName: 'Use .NET 8.x'
  inputs:
    version: 8.x
    
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

# Step 2: Build the Solution
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:Configuration=$(buildConfiguration)'
#- task: VSBuild@1
#  inputs:
#    solution: '**/DevInstance.BlazorToolkit.Samples.Client.csproj'
#    msbuildArgs: '/p:Configuration=$(buildConfiguration)'

#- task: VSBuild@1
#  inputs:
#    solution: '**/DevInstance.BlazorToolkit.Samples.csproj'
#    msbuildArgs: '/p:Configuration=$(buildConfiguration)'
